export type AuditEventType =
  | 'CONSENT_GIVEN'
  | 'SCENARIO_SELECTED'
  | 'LANGUAGE_SELECTED'
  | 'COMMUNICATION_SUPPORT_SELECTED'
  | 'LOCATION_PERMISSION_REQUESTED'
  | 'LOCATION_PERMISSION_GRANTED'
  | 'LOCATION_PERMISSION_DENIED'
  | 'LOCATION_ENTERED'
  | 'ACCESS_CONTEXT_CALCULATED'
  | 'SERVICE_MATCH_COMPLETED'
  | 'VIRTUAL_OPTION_DISPLAYED'
  | 'FIRST_NATIONS_SERVICES_REQUESTED'
  | 'CARE_ACCESS_BARRIER_IDENTIFIED'
  | 'QUESTION_ANSWERED'
  | 'ANSWER_REVISED'
  | 'EMERGENCY_STOP_TRIGGERED'
  | 'HANDOFF_VALIDATED'
  | 'RULE_EVALUATED'
  | 'RECOMMENDATION_DISPLAYED'
  | 'CARE_NAVIGATION_DISPLAYED'
  | 'TEACH_BACK_COMPLETED'
  | 'PATIENT_FEEDBACK_SUBMITTED'
  | 'STAFF_REVIEW_SUBMITTED'
  | 'IMPROVEMENT_ITEM_CREATED'
  | 'IMPROVEMENT_STATUS_CHANGED';

export interface AuditEvent {
  id: string;
  sessionId: string;
  eventType: AuditEventType;
  details: Record<string, any>;
  timestamp: string;
}
